Upgrade documentation to FSP 3.5.0
micro-ROS/micro_ros_renesas2estudio_component pull request #26
Opened 2021-12-21 14:37 UTC by Acuadros95

2021-12-21 14:40 UTC, Acuadros95 commented
@mergify backport main foxy

2021-12-22 07:40 UTC, pablogs9 requested changes
![image](https://user-images.githubusercontent.com/7647884/147054233-1bcf5635-e0ae-442d-932f-139933530a1f.png)

In this image, there is a red block. Is this a missconfiguration?

2021-12-22 07:44 UTC, Acuadros95 commented
Its being configured on the image, the block will be ok when that step is finished,

2021-12-22 07:50 UTC, pablogs9 approved these changes

2021-12-22 07:53 UTC, merged