Add FreeRTOS TCP WIFI transport
micro-ROS/micro_ros_renesas2estudio_component pull request #30
Opened 2022-01-14 13:37 UTC by Acuadros95

2022-01-19 09:11 UTC, pablogs9 requested changes

2022-01-19 09:11 UTC, pablogs9 commented on micro_ros_transports.md
> +            .ucSSID  = "test_ssid",
```suggestion
            .ucSSID  = "[YOUR_SSID_HERE]",
            .xPassword.xWPA.cPassphrase = "[YOUR_PSK_HERE]",
```

2022-01-19 09:11 UTC, pablogs9 commented on micro_ros_transports.md
> +
Add a reference to the WiFi module that is supported

2022-01-19 10:49 UTC, Acuadros95 commented on micro_ros_transports.md
> +
Added: https://github.com/micro-ROS/micro_ros_renesas2estudio_component/pull/30/commits/68d1918d9b524d8dc6ff8804285481170d4517b6

2022-01-19 10:55 UTC, pablogs9 requested changes

2022-01-19 10:55 UTC, pablogs9 commented on micro_ros_transports.md
> +         ```
Add another point indicating the command for creating the agent with TCP. Should we add this to other transports also?

2022-01-19 15:07 UTC, Acuadros95 commented on micro_ros_transports.md
> +         ```
Already present on general readme: https://github.com/micro-ROS/micro_ros_renesas2estudio_component/pull/30/commits/8db3545b134a4f57320ed0e6a1e481ebac6ad0a9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56

2022-01-19 15:12 UTC, pablogs9 approved these changes

2022-01-20 13:32 UTC, pablogs9 approved these changes

2022-01-20 13:52 UTC, pablogs9 approved these changes

2022-01-20 13:59 UTC, Acuadros95 commented
@mergify backport foxy main

2022-01-20 13:59 UTC, merged